//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BabyFaceV0Entities : DbContext
    {
        public BabyFaceV0Entities()
            : base("name=BabyFaceV0Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicShape> BasicShapes { get; set; }
        public virtual DbSet<BookOrder> BookOrders { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<ClothesShape> ClothesShapes { get; set; }
        public virtual DbSet<EyesShape> EyesShapes { get; set; }
        public virtual DbSet<FaceAdd> FaceAdds { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Glass> Glasses { get; set; }
        public virtual DbSet<HairColor> HairColors { get; set; }
        public virtual DbSet<HairCut> HairCuts { get; set; }
        public virtual DbSet<SkinColor> SkinColors { get; set; }
    }
}
