//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.BookOrders = new HashSet<BookOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BasicShapeId { get; set; }
        public Nullable<int> HairCutId { get; set; }
        public Nullable<int> SkinColorId { get; set; }
        public Nullable<int> HairColorId { get; set; }
        public Nullable<int> EyesShapeId { get; set; }
        public Nullable<int> GlasseId { get; set; }
        public Nullable<int> FaceAddsId { get; set; }
        public Nullable<int> ClothesShapeId { get; set; }
        public string VectorImagePath { get; set; }
        public string ColoredImagePath { get; set; }
        public string Thumptailpath { get; set; }
    
        public virtual BasicShape BasicShape { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrder> BookOrders { get; set; }
        public virtual ClothesShape ClothesShape { get; set; }
        public virtual EyesShape EyesShape { get; set; }
        public virtual FaceAdd FaceAdd { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Glass Glass { get; set; }
        public virtual HairColor HairColor { get; set; }
        public virtual HairCut HairCut { get; set; }
        public virtual SkinColor SkinColor { get; set; }
    }
}
